// Editorial OS — dummy dataset. Scaled down from the spec's suggested
// volume (50-70 observations etc.) to a smaller set that preserves full
// structural interconnection: the same observation shows up in its own
// record, on its thesis's evolution timeline, as evidence, and inside an
// editorial where relevant — quality of relationships over raw count.
window.EOS_DATA = (function () {
  const MATURITY = { emerging: "○", strengthening: "◉", established: "●", challenged: "◌" };

  const themes = [
    {
      id: "product-judgment",
      name: "Product Judgment",
      maturity: "strengthening",
      belief: "As execution gets cheaper, product judgment becomes more valuable.",
      firstObserved: "Aug 19",
      lastChanged: "Today",
      children: ["prioritization", "measurement", "decision-quality"],
      evolution: [
        { date: "AUG 19", label: "Initial thought", text: "AI is dramatically reducing the cost of producing software." },
        { date: "AUG 31", label: "Household Dashboard", text: "Rapid prototyping made adding features almost frictionless." },
        { date: "SEP 08", label: "Interview Finding", text: "The PM bottleneck shifts toward deciding what deserves to exist." },
        { date: "SEP 16", label: "Farkle", text: "Cheap iteration produced more possible experiments." },
        { date: "TODAY", label: "Analytics Experiment", text: "Measurement needs to evaluate the decision, not simply the feature." },
      ],
      currentBelief: "As execution gets cheaper, PMs need stronger systems for prioritization and measuring decision quality.",
      evidenceFor: ["obs-farkle-analytics", "obs-household-iterations", "obs-pm-interview", "obs-editorial-workflow", "obs-enterprise-ai", "obs-prototype-feedback", "obs-agent-experiments"],
      evidenceAgainst: ["obs-discovery-vs-planning", "obs-low-cost-no-prioritization"],
      openQuestions: [
        "How should PM decision quality actually be measured?",
        "Does cheaper experimentation improve product outcomes?",
        "When is prioritization more expensive than simply running the experiment?",
        "Does this change for regulated organizations?",
      ],
    },
    {
      id: "agentic-workflows",
      name: "Agentic Workflows",
      maturity: "strengthening",
      belief: "Agents and humans should operate the same underlying product.",
      firstObserved: "Aug 27",
      lastChanged: "Sep 15",
      children: ["human-agent-ownership", "shared-state", "permissions"],
      evolution: [
        { date: "AUG 27", label: "Initial thought", text: "Agents kept as a separate 'admin mode' feel bolted-on, not native." },
        { date: "SEP 03", label: "Hermes Canvas", text: "Giving Hermes the same data model as the human surfaced real conflicts." },
        { date: "SEP 09", label: "Household Dashboard", text: "Permission boundaries matter more once an agent can act unattended." },
        { date: "SEP 15", label: "Agent Ownership Draft", text: "Ownership needs to be explicit per-object, not just per-feature." },
      ],
      currentBelief: "Agents and humans should share one product surface with explicit, per-object ownership — not a parallel agent-only mode.",
      evidenceFor: ["obs-hermes-canvas-shared-model", "obs-household-permissions", "obs-kanban-lock", "obs-agent-ownership-draft", "obs-inbox-both-directions"],
      evidenceAgainst: ["obs-agent-ownership-challenge"],
      openQuestions: [
        "Who owns an object an agent created but a human edited?",
        "Should agents ever have write access a human doesn't see live?",
        "What's the right UI for 'an agent is working on this right now'?",
      ],
    },
    {
      id: "ai-interfaces",
      name: "AI Interfaces",
      maturity: "emerging",
      belief: "The best AI interfaces mostly aren't chat.",
      firstObserved: "Sep 05",
      lastChanged: "Sep 12",
      children: ["beyond-chat", "ambient-interfaces", "physical-controls"],
      evolution: [
        { date: "SEP 05", label: "Initial thought", text: "Every new agent product defaults to a chat box — that's the easy path, not the best one." },
        { date: "SEP 09", label: "Home Screen Badge", text: "A badge count communicated more than a chat message would have, with zero reading required." },
        { date: "SEP 12", label: "Household Controller", text: "Physical-feeling controls (Liquid Glass sheets, real toggles) read as more trustworthy than a chat reply for state changes." },
      ],
      currentBelief: "Chat is the fallback interface for AI, not the default — ambient signals and direct manipulation should be tried first.",
      evidenceFor: ["obs-badge-signal", "obs-glass-controller", "obs-canvas-swipe"],
      evidenceAgainst: ["obs-chat-still-wins-open-ended"],
      openQuestions: [
        "When does chat actually beat a direct-manipulation UI?",
        "How do you show agent confidence without a sparkle icon?",
      ],
    },
    {
      id: "building-with-ai",
      name: "Building With AI",
      maturity: "established",
      belief: "Cheap execution changes what's worth prototyping, not just how fast you can ship.",
      firstObserved: "Aug 05",
      lastChanged: "Sep 17",
      children: ["cheap-execution", "rapid-prototyping", "experimentation"],
      evolution: [
        { date: "AUG 05", label: "Initial thought", text: "A working prototype is now cheap enough to be the pitch, not a follow-up to one." },
        { date: "AUG 22", label: "Idea Lab", text: "Publishing every prototype, not just the winners, changed which ideas got picked up by others." },
        { date: "SEP 10", label: "Feedback Loop", text: "A rejection with a reason is worth more than ten ideas with no feedback at all." },
        { date: "SEP 17", label: "Star Rally", text: "A single-device demo proved the core loop before any multiplayer infrastructure was built." },
      ],
      currentBelief: "Build the smallest real version of the core loop first — infrastructure earns its place after the loop is proven fun or useful, not before.",
      evidenceFor: ["obs-idea-lab-publish", "obs-feedback-loop-value", "obs-star-rally-scope", "obs-receipt-roast-speed"],
      evidenceAgainst: [],
      openQuestions: [
        "At what point does skipping infrastructure start costing more than it saves?",
        "How do you know a demo has proven the loop vs. just looked fun once?",
      ],
    },
  ];

  const subNodes = [
    { id: "prioritization", parent: "product-judgment", name: "Prioritization", maturity: "strengthening" },
    { id: "measurement", parent: "product-judgment", name: "Measurement", maturity: "strengthening" },
    { id: "decision-quality", parent: "product-judgment", name: "Decision Quality", maturity: "emerging" },
    { id: "human-agent-ownership", parent: "agentic-workflows", name: "Human / Agent Ownership", maturity: "challenged" },
    { id: "shared-state", parent: "agentic-workflows", name: "Shared State", maturity: "strengthening" },
    { id: "permissions", parent: "agentic-workflows", name: "Permissions", maturity: "emerging" },
    { id: "beyond-chat", parent: "ai-interfaces", name: "Beyond Chat", maturity: "emerging" },
    { id: "ambient-interfaces", parent: "ai-interfaces", name: "Ambient Interfaces", maturity: "strengthening" },
    { id: "physical-controls", parent: "ai-interfaces", name: "Physical Controls", maturity: "emerging" },
    { id: "cheap-execution", parent: "building-with-ai", name: "Cheap Execution", maturity: "established" },
    { id: "rapid-prototyping", parent: "building-with-ai", name: "Rapid Prototyping", maturity: "established" },
    { id: "experimentation", parent: "building-with-ai", name: "Experimentation", maturity: "strengthening" },
  ];

  const observations = [
    { id: "obs-farkle-analytics", theme: "product-judgment", text: "Analytics should describe the decision being evaluated, not simply the UI interaction.", source: "Farkle · Product Decision", when: "Today, 11:42 PM" },
    { id: "obs-tutorial-randomness", theme: "building-with-ai", text: "The tutorial became easier to understand after randomness was intentionally constrained.", source: "Farkle · Experiment", when: "Today, 9:14 AM" },
    { id: "obs-household-iterations", theme: "product-judgment", text: "Adding a feature to the household dashboard took an afternoon instead of a sprint — the bottleneck moved to deciding if it was worth adding.", source: "Household Dashboard · Iteration", when: "Aug 31" },
    { id: "obs-pm-interview", theme: "product-judgment", text: "Every PM interviewed described the same shift: less time writing specs, more time deciding what deserves a spec.", source: "Interview · AI PM Research", when: "Sep 08" },
    { id: "obs-editorial-workflow", theme: "product-judgment", text: "The editorial checklist (voice, thesis, skeptic, overlap) is itself a judgment tool, not a content tool.", source: "Editorial Workflow", when: "Sep 14" },
    { id: "obs-enterprise-ai", theme: "product-judgment", text: "Enterprise teams with the most AI tooling access shipped the least — they hadn't built judgment for what to build.", source: "Enterprise AI Experience", when: "Sep 11" },
    { id: "obs-prototype-feedback", theme: "product-judgment", text: "A typed rejection reason changed the next day's idea generation more than five more ideas would have.", source: "Idea Lab · Feedback Loop", when: "Sep 10" },
    { id: "obs-agent-experiments", theme: "product-judgment", text: "Letting Hermes generate ideas autonomously surfaced how much of 'good taste' is actually just applied judgment.", source: "Agent Experiments", when: "Sep 09" },
    { id: "obs-discovery-vs-planning", theme: "product-judgment", text: "Faster execution sometimes enables discovery that planning would miss entirely.", source: "Farkle · Counter-observation", when: "Sep 13" },
    { id: "obs-low-cost-no-prioritization", theme: "product-judgment", text: "Some low-cost experiments don't require heavy prioritization — the cost of being wrong is just too low to matter.", source: "Household Dashboard · Counter-observation", when: "Sep 07" },

    { id: "obs-hermes-canvas-shared-model", theme: "agentic-workflows", text: "Hermes and the human read/write the exact same cards and to-dos — no separate 'agent inbox' silo.", source: "Hermes Canvas", when: "Sep 03" },
    { id: "obs-household-permissions", theme: "agentic-workflows", text: "Once Hermes could act on the household dashboard unattended, the missing piece wasn't more capability — it was scoped permission.", source: "Household Dashboard", when: "Sep 09" },
    { id: "obs-kanban-lock", theme: "agentic-workflows", text: "A dispatcher lock file prevents two agents from claiming the same task — a primitive human tools never needed.", source: "Kanban Dispatcher", when: "Sep 05" },
    { id: "obs-agent-ownership-draft", theme: "agentic-workflows", text: "Drafted a per-object 'owner' field (human | agent | shared) instead of a single global agent-mode toggle.", source: "Agent Ownership Draft", when: "Sep 15" },
    { id: "obs-inbox-both-directions", theme: "agentic-workflows", text: "The canvas inbox works both ways now — Hermes reads it and the human reads Hermes's replies in the same list.", source: "Hermes Canvas", when: "Sep 06" },
    { id: "obs-agent-ownership-challenge", theme: "agentic-workflows", text: "Per-object ownership adds a real permissions surface to design and explain — a toggle would ship faster.", source: "Agent Ownership Draft · Counter-observation", when: "Sep 15" },

    { id: "obs-badge-signal", theme: "ai-interfaces", text: "A Home Screen badge count communicated 'something changed' without requiring a single word to be read.", source: "Hermes Canvas · Badge", when: "Sep 09" },
    { id: "obs-glass-controller", theme: "ai-interfaces", text: "A physical-feeling toggle for 'night mode' felt more trustworthy than asking Hermes to turn it off in chat.", source: "Household Controller", when: "Sep 12" },
    { id: "obs-canvas-swipe", theme: "ai-interfaces", text: "Swipe-to-reject with a required reason produced better signal than a thumbs-down button would have.", source: "Hermes Canvas · Swipe", when: "Sep 10" },
    { id: "obs-chat-still-wins-open-ended", theme: "ai-interfaces", text: "For genuinely open-ended requests ('build me a prototype'), chat is still the fastest interface by far.", source: "Idea Lab · Counter-observation", when: "Sep 12" },

    { id: "obs-idea-lab-publish", theme: "building-with-ai", text: "Publishing every prototype publicly, including the weird ones, changed which ideas got a second look.", source: "Idea Lab", when: "Aug 22" },
    { id: "obs-feedback-loop-value", theme: "building-with-ai", text: "A visible, browsable history of past feedback made the whole idea-generation loop feel trustworthy instead of a black box.", source: "Idea Lab · Feedback Screen", when: "Sep 10" },
    { id: "obs-star-rally-scope", theme: "building-with-ai", text: "Scoping to a single-device demo (bots simulate other players) proved the game loop in one session instead of a multiplayer backend project.", source: "Star Rally", when: "Sep 17" },
    { id: "obs-receipt-roast-speed", theme: "building-with-ai", text: "A funny, narrow demo (photo → roast) shipped same-session, no backend required beyond a vision API call.", source: "Receipt Roast", when: "Sep 09" },
  ];

  const signals = [
    {
      id: "sig-lenny",
      title: "Why AI makes product managers more important, not less",
      source: "Lenny's Newsletter",
      author: "Lenny Rachitsky",
      when: "2 hours ago",
      summary: "The argument: AI dramatically increases the speed at which teams can experiment.",
      relatedTheme: "product-judgment",
      whyCare: "This intersects directly with your Product Judgment thesis.",
      angle: "extend",
      angleText: "Faster experimentation makes choosing what deserves experimentation more important.",
      draftText: "I've been seeing this in some of my own experiments — the bottleneck moved from \"can we build it\" to \"should we,\" and most teams haven't built the muscle for that second question yet.",
      status: "open",
    },
    {
      id: "sig-agent-ownership",
      title: "The 'who owns this' problem is the real blocker for agentic software",
      source: "Platforms & AI",
      author: "Ben Thompson-adjacent newsletter",
      when: "Yesterday",
      summary: "As agents get real write access, ownership and audit trails — not capability — become the bottleneck.",
      relatedTheme: "agentic-workflows",
      whyCare: "Matches your per-object ownership draft almost exactly.",
      angle: "agree",
      angleText: "Ownership, not capability, is the real bottleneck — my draft already models this per-object rather than as a global toggle.",
      draftText: "Completely agree, and I'd go further: the ownership model needs to be per-object, not a single agent-mode switch — I've been prototyping exactly this on a household dashboard.",
      status: "open",
    },
    {
      id: "sig-chat-ui",
      title: "Everyone is shipping the same chat box, and it's a UX cop-out",
      source: "Interfaces Weekly",
      author: "Design Systems Digest",
      when: "Yesterday",
      summary: "A survey of 40 AI products found nearly all default to a chat panel, even for structured tasks.",
      relatedTheme: "ai-interfaces",
      whyCare: "Directly supports your Beyond Chat thesis — good citation material.",
      angle: "extend",
      angleText: "Chat isn't wrong, it's just the default people reach for before trying anything harder — badges, sheets, and physical controls all beat it for narrow tasks.",
      draftText: "Agreed on the survey finding — though I'd frame it less as \"chat is bad\" and more as \"chat is the fallback, not the default.\" A badge count beat a chat message for the exact same task in something I shipped last week.",
      status: "open",
    },
    {
      id: "sig-prototyping-cost",
      title: "Prototyping cost has fallen 100x — has anyone actually changed how they decide what to build?",
      source: "Software Economics",
      author: "Various",
      when: "2 days ago",
      summary: "Argues most teams still use pre-AI prioritization frameworks despite a collapse in build cost.",
      relatedTheme: "building-with-ai",
      whyCare: "A near-perfect setup for your strongest editorial opportunity this week.",
      angle: "agree",
      angleText: "This is exactly the gap — frameworks built for a world where building was expensive are now measuring the wrong constraint.",
      draftText: "",
      status: "open",
    },
    {
      id: "sig-measurement",
      title: "Most product analytics still measure screens, not decisions",
      source: "Product Craft",
      author: "Product Craft Weekly",
      when: "3 days ago",
      summary: "Critiques event-based analytics for optimizing UI funnels instead of decision quality.",
      relatedTheme: "product-judgment",
      whyCare: "Nearly the same finding as your Farkle analytics observation from today.",
      angle: "example",
      angleText: "I just lived this exact shift — rebuilt Farkle's analytics from screen-tracking to decision-and-outcome tracking this week.",
      draftText: "",
      status: "saved",
    },
    {
      id: "sig-multiplayer",
      title: "Ship the single-player loop before you build multiplayer",
      source: "Indie Game Dev Digest",
      author: "r/gamedev roundup",
      when: "4 days ago",
      summary: "Common advice in game dev now echoed in AI-app building: prove the core loop before the infrastructure.",
      relatedTheme: "building-with-ai",
      whyCare: "You did exactly this with Star Rally this week — good real example to cite.",
      angle: "example",
      angleText: "Scoped a party game prototype to single-device/bot-simulated players first — proved the loop in one session instead of a multiplayer backend build.",
      draftText: "",
      status: "dismissed",
    },
  ];

  const ideas = [
    { id: "idea-execution-bottleneck", title: "Execution is no longer the bottleneck", status: "strengthening", evidence: 7, challenges: 2, projects: 4, lastChanged: "Today", progress: 0.7, theme: "product-judgment" },
    { id: "idea-per-object-ownership", title: "Ownership should be per-object, not a global agent toggle", status: "strengthening", evidence: 5, challenges: 1, projects: 2, lastChanged: "Sep 15", progress: 0.6, theme: "agentic-workflows" },
    { id: "idea-chat-is-fallback", title: "Chat is the fallback interface, not the default", status: "emerging", evidence: 3, challenges: 1, projects: 3, lastChanged: "Sep 12", progress: 0.35, theme: "ai-interfaces" },
    { id: "idea-feedback-over-volume", title: "One rejection with a reason beats ten more untested ideas", status: "ready-to-write", evidence: 4, challenges: 0, projects: 2, lastChanged: "Sep 10", progress: 0.85, theme: "building-with-ai" },
    { id: "idea-regulated-orgs", title: "Does the judgment shift hold in regulated industries?", status: "emerging", evidence: 1, challenges: 0, projects: 0, lastChanged: "Sep 08", progress: 0.1, theme: "product-judgment" },
    { id: "idea-audit-trail", title: "Agent actions need the same audit trail as human ones, not a lighter one", status: "challenged", evidence: 2, challenges: 3, projects: 1, lastChanged: "Sep 15", progress: 0.3, theme: "agentic-workflows" },
    { id: "idea-badge-vs-notification", title: "A badge is a better unit of agent-to-human signal than a notification", status: "strengthening", evidence: 3, challenges: 0, projects: 2, lastChanged: "Sep 09", progress: 0.55, theme: "ai-interfaces" },
  ];

  const editorials = [
    {
      id: "ed-disagreement",
      title: "The Prototype Got Useful When People Disagreed With It",
      status: "ready-for-review",
      thesis: "Prototypes become valuable when real disagreement exposes assumptions.",
      whyExists: "The feedback-loop work this week made the value of disagreement concrete and demoable, not just a nice idea.",
      evidenceUsed: ["obs-prototype-feedback", "obs-feedback-loop-value"],
      related: ["idea-feedback-over-volume"],
      article: "For two weeks the idea pipeline ran without a single rejection reason attached to it — just accept or delete. It felt productive. It wasn't. The moment a \"no, and here's why\" started flowing back into the next day's ideas, the whole thing sharpened...",
      voiceCheck: "pass",
      thesisCheck: "pass",
      skepticCheck: "warn",
      skepticNote: "One unresolved objection: does this generalize past a single-user feedback loop?",
      overlapCheck: "pass",
      updated: "Sep 16",
    },
    {
      id: "ed-pm-bottleneck",
      title: "What Happens to Product Management When Building Software Gets Cheap?",
      status: "developing",
      thesis: "As execution gets cheaper, product judgment becomes more valuable.",
      whyExists: "This week's strongest editorial opportunity — nine observations, four projects, two interview findings, and two live counterarguments all point the same direction.",
      evidenceUsed: ["obs-farkle-analytics", "obs-household-iterations", "obs-pm-interview", "obs-enterprise-ai"],
      related: ["idea-execution-bottleneck"],
      article: "",
      voiceCheck: "pending",
      thesisCheck: "pending",
      skepticCheck: "pending",
      overlapCheck: "pending",
      updated: "Today",
    },
    {
      id: "ed-ownership-model",
      title: "Agent Ownership Isn't a Toggle, It's a Field",
      status: "developing",
      thesis: "Agents and humans should operate the same underlying product, with ownership tracked per object.",
      whyExists: "The ownership draft this week is concrete enough to argue for directly, and the counter-observation (a toggle ships faster) makes it a real argument, not a strawman.",
      evidenceUsed: ["obs-agent-ownership-draft", "obs-hermes-canvas-shared-model"],
      related: ["idea-per-object-ownership"],
      article: "",
      voiceCheck: "pending",
      thesisCheck: "pending",
      skepticCheck: "pending",
      overlapCheck: "pending",
      updated: "Sep 15",
    },
    {
      id: "ed-badge-signal",
      title: "The Best Agent Notification Is Sometimes Just a Number",
      status: "ready-for-review",
      thesis: "Ambient signals beat chat messages for narrow, well-understood state changes.",
      whyExists: "The badge and swipe-feedback work gave a small, concrete, demoable case for the Beyond Chat thesis.",
      evidenceUsed: ["obs-badge-signal", "obs-canvas-swipe"],
      related: ["idea-badge-vs-notification"],
      article: "Somewhere between \"no notification\" and \"another chat message to read,\" there's a badge. A single number, sitting on an icon you were going to look at anyway...",
      voiceCheck: "pass",
      thesisCheck: "pass",
      skepticCheck: "pass",
      overlapCheck: "pass",
      updated: "Sep 11",
    },
    {
      id: "ed-published-judgment",
      title: "Cheap Execution Didn't Kill Product Management — It Changed What It Measures",
      status: "published",
      thesis: "The first version of the Product Judgment thesis, before the analytics-decision framing sharpened it.",
      whyExists: "Published early version — since deepened by this week's Farkle analytics work.",
      evidenceUsed: ["obs-household-iterations"],
      related: ["idea-execution-bottleneck"],
      article: "",
      voiceCheck: "pass",
      thesisCheck: "pass",
      skepticCheck: "pass",
      overlapCheck: "pass",
      updated: "Sep 02",
    },
    {
      id: "ed-published-prototyping",
      title: "Publish the Weird Prototypes Too",
      status: "published",
      thesis: "Publishing every prototype publicly, not just the winners, changes which ideas get a second look.",
      whyExists: "Published reflection on the first month of Idea Lab.",
      evidenceUsed: ["obs-idea-lab-publish"],
      related: ["idea-feedback-over-volume"],
      article: "",
      voiceCheck: "pass",
      thesisCheck: "pass",
      skepticCheck: "pass",
      overlapCheck: "pass",
      updated: "Aug 25",
    },
  ];

  const archive = [
    { date: "Sep 18", kind: "deepen", title: "Product Judgment" },
    { date: "Sep 17", kind: "capture", title: "Star Rally scope decision" },
    { date: "Sep 16", kind: "new-idea", title: "Prototype disagreement" },
    { date: "Sep 15", kind: "challenge", title: "Agent Ownership" },
    { date: "Sep 15", kind: "deepen", title: "Agentic Workflows" },
    { date: "Sep 14", kind: "capture", title: "Editorial workflow as a judgment tool" },
    { date: "Sep 12", kind: "deepen", title: "AI Interfaces" },
    { date: "Sep 11", kind: "editorial", title: "The Best Agent Notification Is Sometimes Just a Number" },
    { date: "Sep 10", kind: "capture", title: "Feedback loop value" },
    { date: "Sep 09", kind: "capture", title: "Home Screen badge signal" },
    { date: "Sep 08", kind: "capture", title: "PM interview finding" },
    { date: "Sep 05", kind: "new-idea", title: "Beyond chat" },
    { date: "Sep 03", kind: "capture", title: "Hermes Canvas shared model" },
    { date: "Aug 31", kind: "deepen", title: "Household Dashboard iteration speed" },
    { date: "Aug 25", kind: "editorial", title: "Publish the Weird Prototypes Too" },
    { date: "Aug 22", kind: "capture", title: "Idea Lab publish decision" },
    { date: "Aug 19", kind: "new-idea", title: "Product Judgment" },
  ];

  const weekly = {
    range: "Sep 12–18",
    observations: 12,
    strengthened: 4,
    challenged: 1,
    emerged: 2,
    whatChanged: [
      {
        theme: "product-judgment",
        from: "AI makes execution cheaper.",
        to: "Cheap execution shifts the PM bottleneck toward decision quality.",
        why: "Farkle experimentation + interview answers + analytics work.",
      },
    ],
    bestOpportunity: {
      editorialId: "ed-pm-bottleneck",
      title: "What Happens to Product Management When Building Software Gets Cheap?",
      observations: 9,
      projects: 4,
      interviewFindings: 2,
      counterarguments: 2,
    },
  };

  return { MATURITY, themes, subNodes, observations, signals, ideas, editorials, archive, weekly };
})();
